// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Chunk struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Used                 int64    `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Replicas             []string `protobuf:"bytes,4,rep,name=replicas,proto3" json:"replicas,omitempty"`
	FileUUID             string   `protobuf:"bytes,5,opt,name=FileUUID,proto3" json:"FileUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_cbb8dec29095fa82, []int{0}
}
func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (dst *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(dst, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Chunk) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Chunk) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *Chunk) GetReplicas() []string {
	if m != nil {
		return m.Replicas
	}
	return nil
}

func (m *Chunk) GetFileUUID() string {
	if m != nil {
		return m.FileUUID
	}
	return ""
}

type File struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ReplicaNum           int32    `protobuf:"varint,4,opt,name=replica_num,json=replicaNum,proto3" json:"replica_num,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Chunks               []*Chunk `protobuf:"bytes,7,rep,name=chunks,proto3" json:"chunks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_cbb8dec29095fa82, []int{1}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetReplicaNum() int32 {
	if m != nil {
		return m.ReplicaNum
	}
	return 0
}

func (m *File) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *File) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *File) GetChunks() []*Chunk {
	if m != nil {
		return m.Chunks
	}
	return nil
}

type FileChunkData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileChunkData) Reset()         { *m = FileChunkData{} }
func (m *FileChunkData) String() string { return proto.CompactTextString(m) }
func (*FileChunkData) ProtoMessage()    {}
func (*FileChunkData) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_cbb8dec29095fa82, []int{2}
}
func (m *FileChunkData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileChunkData.Unmarshal(m, b)
}
func (m *FileChunkData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileChunkData.Marshal(b, m, deterministic)
}
func (dst *FileChunkData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChunkData.Merge(dst, src)
}
func (m *FileChunkData) XXX_Size() int {
	return xxx_messageInfo_FileChunkData.Size(m)
}
func (m *FileChunkData) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChunkData.DiscardUnknown(m)
}

var xxx_messageInfo_FileChunkData proto.InternalMessageInfo

func (m *FileChunkData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *FileChunkData) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type GenericResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  int64    `protobuf:"varint,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericResponse) Reset()         { *m = GenericResponse{} }
func (m *GenericResponse) String() string { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()    {}
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_cbb8dec29095fa82, []int{3}
}
func (m *GenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericResponse.Unmarshal(m, b)
}
func (m *GenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericResponse.Marshal(b, m, deterministic)
}
func (dst *GenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericResponse.Merge(dst, src)
}
func (m *GenericResponse) XXX_Size() int {
	return xxx_messageInfo_GenericResponse.Size(m)
}
func (m *GenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericResponse proto.InternalMessageInfo

func (m *GenericResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GenericResponse) GetMsg() int64 {
	if m != nil {
		return m.Msg
	}
	return 0
}

type CreateFileResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  int64    `protobuf:"varint,2,opt,name=msg,proto3" json:"msg,omitempty"`
	File                 *File    `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFileResponse) Reset()         { *m = CreateFileResponse{} }
func (m *CreateFileResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFileResponse) ProtoMessage()    {}
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_cbb8dec29095fa82, []int{4}
}
func (m *CreateFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileResponse.Unmarshal(m, b)
}
func (m *CreateFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileResponse.Marshal(b, m, deterministic)
}
func (dst *CreateFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileResponse.Merge(dst, src)
}
func (m *CreateFileResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFileResponse.Size(m)
}
func (m *CreateFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileResponse proto.InternalMessageInfo

func (m *CreateFileResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateFileResponse) GetMsg() int64 {
	if m != nil {
		return m.Msg
	}
	return 0
}

func (m *CreateFileResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*Chunk)(nil), "pb.Chunk")
	proto.RegisterType((*File)(nil), "pb.File")
	proto.RegisterType((*FileChunkData)(nil), "pb.FileChunkData")
	proto.RegisterType((*GenericResponse)(nil), "pb.GenericResponse")
	proto.RegisterType((*CreateFileResponse)(nil), "pb.CreateFileResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChunkServerClient is the client API for ChunkServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChunkServerClient interface {
	CreateFile(ctx context.Context, opts ...grpc.CallOption) (ChunkServer_CreateFileClient, error)
	RemoveFile(ctx context.Context, in *File, opts ...grpc.CallOption) (*GenericResponse, error)
	AppendFile(ctx context.Context, opts ...grpc.CallOption) (ChunkServer_AppendFileClient, error)
}

type chunkServerClient struct {
	cc *grpc.ClientConn
}

func NewChunkServerClient(cc *grpc.ClientConn) ChunkServerClient {
	return &chunkServerClient{cc}
}

func (c *chunkServerClient) CreateFile(ctx context.Context, opts ...grpc.CallOption) (ChunkServer_CreateFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChunkServer_serviceDesc.Streams[0], "/pb.ChunkServer/CreateFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &chunkServerCreateFileClient{stream}
	return x, nil
}

type ChunkServer_CreateFileClient interface {
	Send(*FileChunkData) error
	CloseAndRecv() (*CreateFileResponse, error)
	grpc.ClientStream
}

type chunkServerCreateFileClient struct {
	grpc.ClientStream
}

func (x *chunkServerCreateFileClient) Send(m *FileChunkData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chunkServerCreateFileClient) CloseAndRecv() (*CreateFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CreateFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chunkServerClient) RemoveFile(ctx context.Context, in *File, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/pb.ChunkServer/RemoveFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkServerClient) AppendFile(ctx context.Context, opts ...grpc.CallOption) (ChunkServer_AppendFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChunkServer_serviceDesc.Streams[1], "/pb.ChunkServer/AppendFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &chunkServerAppendFileClient{stream}
	return x, nil
}

type ChunkServer_AppendFileClient interface {
	Send(*FileChunkData) error
	CloseAndRecv() (*GenericResponse, error)
	grpc.ClientStream
}

type chunkServerAppendFileClient struct {
	grpc.ClientStream
}

func (x *chunkServerAppendFileClient) Send(m *FileChunkData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chunkServerAppendFileClient) CloseAndRecv() (*GenericResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(GenericResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChunkServerServer is the server API for ChunkServer service.
type ChunkServerServer interface {
	CreateFile(ChunkServer_CreateFileServer) error
	RemoveFile(context.Context, *File) (*GenericResponse, error)
	AppendFile(ChunkServer_AppendFileServer) error
}

func RegisterChunkServerServer(s *grpc.Server, srv ChunkServerServer) {
	s.RegisterService(&_ChunkServer_serviceDesc, srv)
}

func _ChunkServer_CreateFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChunkServerServer).CreateFile(&chunkServerCreateFileServer{stream})
}

type ChunkServer_CreateFileServer interface {
	SendAndClose(*CreateFileResponse) error
	Recv() (*FileChunkData, error)
	grpc.ServerStream
}

type chunkServerCreateFileServer struct {
	grpc.ServerStream
}

func (x *chunkServerCreateFileServer) SendAndClose(m *CreateFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chunkServerCreateFileServer) Recv() (*FileChunkData, error) {
	m := new(FileChunkData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChunkServer_RemoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerServer).RemoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChunkServer/RemoveFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerServer).RemoveFile(ctx, req.(*File))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkServer_AppendFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChunkServerServer).AppendFile(&chunkServerAppendFileServer{stream})
}

type ChunkServer_AppendFileServer interface {
	SendAndClose(*GenericResponse) error
	Recv() (*FileChunkData, error)
	grpc.ServerStream
}

type chunkServerAppendFileServer struct {
	grpc.ServerStream
}

func (x *chunkServerAppendFileServer) SendAndClose(m *GenericResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chunkServerAppendFileServer) Recv() (*FileChunkData, error) {
	m := new(FileChunkData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChunkServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ChunkServer",
	HandlerType: (*ChunkServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RemoveFile",
			Handler:    _ChunkServer_RemoveFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateFile",
			Handler:       _ChunkServer_CreateFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "AppendFile",
			Handler:       _ChunkServer_AppendFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_cbb8dec29095fa82) }

var fileDescriptor_service_cbb8dec29095fa82 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xcd, 0x66, 0x9d, 0x10, 0x8f, 0x89, 0x80, 0x45, 0x42, 0x56, 0x00, 0x61, 0x7c, 0xf2, 0x85,
	0x1c, 0xc2, 0x01, 0x24, 0x2e, 0x44, 0x89, 0x40, 0x5c, 0x72, 0x58, 0x14, 0xa9, 0xb7, 0x68, 0x63,
	0x4f, 0x5b, 0xab, 0xb1, 0xbd, 0xf2, 0xda, 0x39, 0xb4, 0x9f, 0xd5, 0xef, 0xe8, 0x3f, 0x55, 0x3b,
	0x76, 0xdc, 0xaa, 0x4d, 0x2b, 0xf5, 0xf6, 0xe6, 0x8d, 0x67, 0xde, 0x7b, 0xe3, 0x85, 0xb1, 0xc1,
	0x72, 0x9f, 0xc6, 0x38, 0xd5, 0x65, 0x51, 0x15, 0xa2, 0xaf, 0xb7, 0xe1, 0x15, 0x0c, 0x16, 0xe7,
	0x75, 0x7e, 0x21, 0x04, 0x38, 0xeb, 0xf5, 0xbf, 0xa5, 0xcf, 0x02, 0x16, 0xb9, 0x92, 0xb0, 0xe5,
	0x4c, 0x7a, 0x89, 0x7e, 0x3f, 0x60, 0x11, 0x97, 0x84, 0x2d, 0x57, 0x1b, 0x4c, 0x7c, 0xde, 0x70,
	0x16, 0x8b, 0x09, 0x8c, 0x4a, 0xd4, 0xbb, 0x34, 0x56, 0xc6, 0x77, 0x02, 0x1e, 0xb9, 0xb2, 0xab,
	0x6d, 0xef, 0x4f, 0xba, 0x43, 0xda, 0x3d, 0xa0, 0xdd, 0x5d, 0x1d, 0xde, 0x30, 0x70, 0x6c, 0x71,
	0x54, 0xfc, 0x23, 0xb8, 0xa7, 0xe9, 0x0e, 0x37, 0xb9, 0xca, 0x1a, 0x07, 0xae, 0x1c, 0x59, 0x62,
	0xa5, 0x32, 0xec, 0x9c, 0xf1, 0x7b, 0xce, 0xbe, 0x80, 0xd7, 0xaa, 0x6e, 0xf2, 0x3a, 0xf3, 0x9d,
	0x80, 0x45, 0x03, 0x09, 0x2d, 0xb5, 0xaa, 0x33, 0xf1, 0x19, 0x20, 0x2e, 0x51, 0x55, 0x98, 0x6c,
	0x54, 0x45, 0x66, 0xb8, 0x74, 0x5b, 0x66, 0x5e, 0xd9, 0x76, 0xad, 0x93, 0x43, 0x7b, 0xd8, 0xb4,
	0x5b, 0x66, 0x5e, 0x89, 0xaf, 0x30, 0x8c, 0xed, 0xa5, 0x8c, 0xff, 0x2a, 0xe0, 0x91, 0x37, 0x73,
	0xa7, 0x7a, 0x3b, 0xa5, 0xdb, 0xc9, 0xb6, 0x11, 0xfe, 0x86, 0xb1, 0x8d, 0x43, 0xe4, 0x52, 0x55,
	0xca, 0xda, 0x4c, 0x54, 0xa5, 0x28, 0xd7, 0x6b, 0x49, 0xf8, 0xd9, 0x5c, 0xe1, 0x0f, 0x78, 0xf3,
	0x17, 0x73, 0x2c, 0xd3, 0x58, 0xa2, 0xd1, 0x45, 0x6e, 0x28, 0x6a, 0x5c, 0x24, 0x48, 0x3b, 0xb8,
	0x24, 0x2c, 0xde, 0x02, 0xcf, 0xcc, 0x59, 0xfb, 0x5f, 0x2c, 0x0c, 0x4f, 0x40, 0x2c, 0x28, 0x89,
	0x35, 0xf0, 0xb2, 0x59, 0xf1, 0x09, 0x1c, 0x6b, 0x80, 0x8e, 0xe9, 0xcd, 0x46, 0x36, 0x17, 0x6d,
	0x21, 0x76, 0x76, 0xcd, 0xc0, 0xa3, 0x44, 0xff, 0xb1, 0xdc, 0x63, 0x29, 0x7e, 0x01, 0xdc, 0x29,
	0x89, 0x77, 0x87, 0xaf, 0xbb, 0xd0, 0x93, 0x0f, 0x74, 0x98, 0x47, 0x66, 0xc2, 0x5e, 0xc4, 0xc4,
	0x37, 0x00, 0x89, 0x59, 0xb1, 0x6f, 0x86, 0x3b, 0xa9, 0xc9, 0x7b, 0x8b, 0x1e, 0x24, 0x0f, 0x7b,
	0xe2, 0x27, 0xc0, 0x5c, 0x6b, 0xcc, 0x93, 0xa7, 0xb4, 0x8e, 0xcf, 0x45, 0x6c, 0x3b, 0xa4, 0x27,
	0xfe, 0xfd, 0x36, 0x00, 0x00, 0xff, 0xff, 0x69, 0xcd, 0x8e, 0x88, 0xf3, 0x02, 0x00, 0x00,
}
